---
title: " This is Sibei Liu's Acedemic Introduction"
output: 
  html_document:
    toc: true
    toc_float: true
---


# Education Background
09/2019-
Columbia University, School of Public Health

Major: Biostatistics

09/2014-06/2019 
Jilin University, School of Public Health

Major: Information Management & Information System (Medical Information Management)  

Degree: Bachelor of Management & Bachelor of Preventive Medicine


# Publication

￭ Pallavi Misra,**Sibei LIU**, Xiangfei Meng,
What DNA methylation modifications and/or genetic variations interact with childhood maltreatment in the development of depression: A systematic review, Journal of Affective Disorders,Volume 252,2019, Pages 325-333, ISSN 0165-0327.

# Internship Experience
07/2018-10/2018  

Mitacs Summer Internship Program: Child Maltreatment and Genetic Variation in Adult Psychopathology: A Systematic Review                       

Department of Psychiatry at McGill University

Supervisor: Dr Xiangfei Meng
Responsibility:

Followed the standard process of Meta-analysis: 

￭ Extracted available data and completed the quality evaluation for the screened paper.

￭ Did the heterogeneity analysis, divided and summarized quantitative and qualitative parts.

# Research Experience 
03/2018-05/2018 
The Influencing Factor of Teenager Smoking in Liaoning Province (A Global Youth Tobacco Survey in Liaoning )                      
Department of Epidemiology and Health Statistics at Jilin University

Supervisor: Associate Prof. Lina JIN, Associate Prof Yan Yao 

Responsibility:

￭ Determined the innovative perspective of data analysis.

￭ Used the complex sampling pack in SPSS to analyze multistage stratified cluster sampling, including doing the Frequency to describe the data distribution, completing the Chi-square analysis and the logistic analysis to find risk factors of teenager smoking.

￭ Wrote the manuscript. 


# Honors & Awards
05/2018 China Scholarship Council- Mitacs Summer Internship funding (More than 30000RMB ) 

09/2016 & 09/2018 The First Scholarship in Academic Years 2015-16 and 2016-17 at Jilin University (5%)

09/2015 The Second Scholarship in Academic Year 2014-2015 at Jilin University (10%)
